# GoReleaser configuration
# https://goreleaser.com

project_name: mosquitto_exporter

before:
  hooks:
    - go mod tidy

builds:
  - id: mosquitto_exporter
    main: .
    binary: mosquitto_exporter
    env:
      - CGO_ENABLED=0
    buildvcs: false
    trimpath: true
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.IMAGE_NAME }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.IMAGE_NAME }}:latest"
      - "docker.io/{{ .Env.DOCKERHUB_USERNAME }}/mosquitto_exporter:{{ .Version }}"
      - "docker.io/{{ .Env.DOCKERHUB_USERNAME }}/mosquitto_exporter:latest"
    dockerfile: Dockerfile
    use: buildx
    goos: [linux]
    goarch: [amd64, arm64]
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
    skip_push: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'