{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: {{ .Values.podDisruptionBudget.apiVersion | default "policy/v1" }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "mosquitto_exporter.fullname" . }}
  labels:
    {{- include "mosquitto_exporter.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mosquitto_exporter.selectorLabels" . | nindent 6 }}
{{- end }}