{{- $createSecret := false -}}
{{- if not .Values.mqtt.auth.existingSecret -}}
{{- if or .Values.mqtt.auth.username .Values.mqtt.auth.password -}}{{- $createSecret = true -}}{{- end -}}
{{- end -}}
{{- if $createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto_exporter.fullname" . }}
  labels:
    {{- include "mosquitto_exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mqtt.auth.usernameKey | default "username" }}: {{ .Values.mqtt.auth.username | quote }}
  {{ .Values.mqtt.auth.passwordKey | default "password" }}: {{ .Values.mqtt.auth.password | quote }}
{{- end }}