apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto_exporter.fullname" . }}
  labels:
    {{- include "mosquitto_exporter.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.prometheus.scrapeAnnotations }}
  annotations:
    {{- if .Values.prometheus.scrapeAnnotations }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: {{ .Values.web.telemetryPath | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "mosquitto_exporter.selectorLabels" . | nindent 4 }}